apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-sample-app
  labels:
    app: capstone-sample-app
spec:
 selector:
    matchLabels:
      app: capstone-sample-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: capstone-sample-app
    spec:
      containers:
        - name: capstone-sample-app
          image: 251557857946.dkr.ecr.us-west-2.amazonaws.com/capstone-sample-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret