apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-sample-app
  labels:
    app: capstone-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-sample-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-sample-app
    spec:
      containers:
        - image: 251557857946.dkr.ecr.us-west-2.amazonaws.com/capstone-sample-app:latest
          name: capstone-sample-app
          ports:
            - containerPort: 80
              name: http-server
      imagePullSecrets:
        - name: ecr-secret
